/* eslint-disable no-unused-vars */
let skully = '';
skully = skully + '                     .ed"""" """$$$$be.\n';
skully = skully + '                   -"           ^""**$$$e.\n';
skully = skully + '                 ."                   `$$$c\n';
skully = skully + '                /                      "4$$b\n';
skully = skully + '               d  3                      $$$$\n';
skully = skully + '               $  *                   .$$$$$$\n';
skully = skully + '              .$  ^c           $$$$$e$$$$$$$$.\n';
skully = skully + '              d$L  4.         4$$$$$$$$$$$$$$b\n';
skully = skully + '              $$$$b ^ceeeee.  4$$ECL.F*$$$$$$$\n';
skully = skully + '  e$""=.      $$$$P d$$$$F $ $$$$$$$$$- $$$$$$\n';
skully = skully + ' z$$b. ^c     3$$$F "$$$$b   $"$$$$$$$  $$$$*"      .=""$c\n';
skully = skully + '4$$$$L        $$P"  "$$b   .$ $$$$$...e$$        .=  e$$$.\n';
skully = skully + '^*$$$$$c  %..   *c    ..    $$ 3$$$$$$$$$$eF     zP  d$$$$$\n';
skully = skully + '  "**$$$ec   "   %ce""    $$$  $$$$$$$$$$*    .r" =$$$$P""\n';
skully = skully + '        "*$b.  "c  *$e.    *** d$$$$$"L$$    .d"  e$$***"\n';
skully = skully + '          ^*$$c ^$c $$$      4J$$$$$% $$$ .e*".eeP"\n';
skully = skully + '             "$$$$$$"`$=e....$*$$**$cz$$" "..d$*"\n';
skully = skully + '               "*$$$  *=%4.$ L L$ P3$$$F $$$P"\n';
skully = skully + '                  "$   "%*ebJLzb$e$$$$$b $P"\n';
skully = skully + '                    %..      4$$$$$$$$$$ "\n';
skully = skully + '                     $$$e   z$$$$$$$$$$%\n';
skully = skully + '                      "*$c  "$$$$$$$P"\n';
skully = skully + '                       ."""*$$$$$$$$bc\n';
skully = skully + '                    .-"    .$***$$$"""*e.\n';
skully = skully + '                 .-"    .e$"     "*$c  ^*b.\n';
skully = skully + '          .=*""""    .e$*"          "*bc  "*$e..\n';
skully = skully + '        .$"        .z*"               ^*$e.   "*****e.\n';
skully = skully + '        $$ee$c   .d"                     "*$.        3.\n';
skully = skully + '        ^*$E")$..$"                         *   .ee==d%\n';
skully = skully + '           $.d$$$*                           *  J$$$e*\n';
skully = skully + '            """""                              "$$$"\n';
